### ISSUE TITLE
postfix doesn't build on kernel 4.0 due to uname checks

### ISSUE THREAD

**Issue by teh** [vdukhovni/postfix#4]
Checking for `uname` instead of features seems like a bad idea in general, but the easiest fix would probably adding a 4.x branch in https://github.com/vdukhovni/postfix/blob/master/postfix/makedefs#L423

**Comment by vdukhovni** [comment]
Postfix is not maintained at Github.  It is mirrored into Github from upstream.  To report issues with Postfix please post to the postfix-users mailing list after searching the archives for similar reports.
